spring:
  application:
    name: bmark-backend
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/bmark}
      username: ${MONGO_USERNAME:root}
      password: ${MONGO_PASSWORD:root}

server:
  port: ${PORT:9090}