spring:
  application:
    name: bmark-backend
  data:
    mongodb:
      uri: mongodb://${DB_USERNAME:root}:${DB_PASSWORD:root}@${DB_HOST:localhost}:${DB_PORT:27017}/${DB_DATABASE:bmark}?authSource=admin

server:
  port: ${PORT:9090}
  error:
    include-message: always
    include-stacktrace: never
    include-binding-errors: always
springdoc:
  swagger-ui:
    enabled: false
---

spring:
  config:
    activate:
      on-profile: dev
springdoc:
  swagger-ui:
    enabled: true
    path: /docs
    display-operation-id: true
    display-request-duration: true
  api-docs:
    path: /docs/json
